databases:
  - name: conectio-db
    plan: free
    databaseName: conectio
    user: conectio_user

services:
  - type: web
    name: conectio-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_superuser_env && python manage.py seed_users --clear && python manage.py seed_posts"
    startCommand: gunicorn conectio_project.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: conectio-db
          property: connectionURI
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
